// GENERIERT aus world_sprites/generated_longlist/manifest.json (Welle 34).
// Monster-Sprite-Registrierung fürs Frontend. Nicht von Hand editieren.
window.LONGLIST_MONSTERS = [
  {k:"creature_marsh_rat_swarm",n:"Sumpfratten-Schwarm"},
  {k:"creature_carrion_crow",n:"Aaskrähe"},
  {k:"creature_giant_centipede",n:"Riesenhundertfüßer"},
  {k:"creature_blood_leech_cluster",n:"Blutegel-Klumpen"},
  {k:"creature_thornback_hare",n:"Dornrücken-Hase"},
  {k:"creature_burrow_grub",n:"Wühlmade"},
  {k:"creature_glass_wing_moth",n:"Glasflügelmotte"},
  {k:"creature_ember_wasp",n:"Glutwespe"},
  {k:"creature_chittering_spider_nest",n:"Klickerspinnen-Nest"},
  {k:"creature_bog_toad",n:"Moor-Kröte"},
  {k:"creature_briar_imp",n:"Dornenkobold"},
  {k:"creature_dire_wolf",n:"Schreckenswolf"},
  {k:"creature_silverback_boar",n:"Silberrücken-Eber"},
  {k:"creature_grasping_kelp",n:"Greifender Tang"},
  {k:"creature_riverbank_crocodilian",n:"Flussufer-Krokodil"},
  {k:"creature_panther_shade",n:"Schattenpanther"},
  {k:"creature_glacier_lynx",n:"Gletscher-Luchs"},
  {k:"creature_dune_strider",n:"Dünenschreiter"},
  {k:"creature_hyena_pack_leader",n:"Hyänen-Anführerin"},
  {k:"creature_normal_hyena",n:"Hyäne"},
  {k:"creature_shrike_falcon",n:"Würger-Falke"},
  {k:"creature_grove_stag_corrupted",n:"Verdorbener Hirsch"},
  {k:"creature_swamp_otter_clan",n:"Sumpfotter-Clan"},
  {k:"creature_thornmaw",n:"Dornenschlund"},
  {k:"creature_iron_horn_aurochs",n:"Eisenhorn-Auerochse"},
  {k:"creature_ridgeback_drake",n:"Kammrücken-Drachling"},
  {k:"creature_glacier_juggernaut_bear",n:"Gletscher-Berserker-Bär"},
  {k:"creature_dune_terror_worm",n:"Dünen-Schreckenswurm"},
  {k:"creature_canyon_wyrm",n:"Schluchtwyvern"},
  {k:"creature_marsh_naga",n:"Sumpf-Naga"},
  {k:"creature_bog_titan_elk",n:"Moor-Titanelch"},
  {k:"creature_road_brigand",n:"Wegelagerer"},
  {k:"creature_brigand_archer",n:"Wegelagerer-Schütze"},
  {k:"creature_brigand_brute",n:"Brutaler Bandit"},
  {k:"creature_brigand_captain",n:"Räuber-Hauptmann"},
  {k:"creature_smoke_bandit",n:"Rauch-Schurke"},
  {k:"creature_deserter_soldier",n:"Deserteur"},
  {k:"creature_witch_hunter_renegade",n:"Abtrünniger Hexenjäger"},
  {k:"creature_slaver_with_chain",n:"Sklaventreiber"},
  {k:"creature_pit_dog_handler",n:"Hundeführer"},
  {k:"creature_pit_dog",n:"Kampfhund"},
  {k:"creature_grin_goblin_scrapper",n:"Grinsekobold"},
  {k:"creature_grin_goblin_shaman",n:"Kobold-Schamane"},
  {k:"creature_grin_goblin_warbeast_rider",n:"Kobold-Reiter"},
  {k:"creature_warboar_mount",n:"Kampfeber"},
  {k:"creature_grin_goblin_warchief",n:"Kobold-Kriegshäuptling"},
  {k:"creature_hobgoblin_legionnaire",n:"Hobgoblin-Legionär"},
  {k:"creature_orgrim_basher",n:"Orgrim-Schläger"},
  {k:"creature_blood_kin_warrior",n:"Blutsippe-Krieger"},
  {k:"creature_blood_kin_screamer",n:"Blutsippe-Schreier"},
  {k:"creature_ash_druid",n:"Aschdruide"},
  {k:"creature_silent_cultist",n:"Stiller Kultist"},
  {k:"creature_void_speaker",n:"Leerensprecher"},
  {k:"creature_swamp_witch",n:"Sumpf-Hexe"},
  {k:"creature_shambling_corpse",n:"Schlurfender Leichnam"},
  {k:"creature_plague_walker",n:"Pest-Wanderer"},
  {k:"creature_rotmaw",n:"Faulschlund"},
  {k:"creature_husk_runner",n:"Hülle-Sprinter"},
  {k:"creature_bone_skirmisher",n:"Knochen-Plänkler"},
  {k:"creature_bone_archer",n:"Knochen-Schütze"},
  {k:"creature_armored_revenant",n:"Gepanzerter Wiedergänger"},
  {k:"creature_grave_drinker_ghoul",n:"Grabtrinker"},
  {k:"creature_wailing_specter",n:"Wehklagender Geist"},
  {k:"creature_lantern_wight",n:"Laternen-Wicht"},
  {k:"creature_crypt_lord",n:"Gruft-Fürst"},
  {k:"creature_lich_archivist",n:"Lich-Archivar"},
  {k:"creature_vampire_lordling",n:"Vampir-Lord"},
  {k:"creature_ossuary_titan",n:"Beinhaus-Titan"},
  {k:"creature_will_o_wisp",n:"Irrlicht"},
  {k:"creature_mire_drowner",n:"Tümpelfrau"},
  {k:"creature_treant_warden",n:"Baumriese"},
  {k:"creature_dryad_hunter",n:"Dryadenjägerin"},
  {k:"creature_fae_changeling",n:"Wechselbalg"},
  {k:"creature_fire_elemental_small",n:"Kleines Feuer-Elementar"},
  {k:"creature_fire_elemental_lord",n:"Feuer-Lord"},
  {k:"creature_water_elemental_brine",n:"Salzwasser-Elementar"},
  {k:"creature_stone_elemental_lumbering",n:"Stein-Koloss"},
  {k:"creature_lightning_djinn",n:"Blitzdschinn"},
  {k:"creature_frost_revenant_yeti",n:"Frost-Yeti"},
  {k:"creature_starlight_unicorn_corrupt",n:"Verdorbenes Einhorn"},
  {k:"creature_thing_in_the_well",n:"Brunnenwesen"},
  {k:"creature_eyeless_pilgrim",n:"Augenloser Pilger"},
  {k:"creature_choir_of_mouths",n:"Mund-Chor"},
  {k:"creature_hollow_marrow_serpent",n:"Mark-Schlange"},
  {k:"creature_geometry_horror",n:"Geometriegrauen"},
  {k:"creature_drowned_cathedral_thing",n:"Versunkene Kathedrale"},
  {k:"creature_inverted_pilgrim_swarm",n:"Umgestülpte Pilger"},
  {k:"creature_star_mote_imp",n:"Sternpartikel"},
  {k:"creature_clay_homunculus",n:"Lehm-Homunkulus"},
  {k:"creature_iron_sentinel",n:"Eiserner Wächter"},
  {k:"creature_bone_ossuary_construct",n:"Beinhaus-Konstrukt"},
  {k:"creature_arcane_orrery_guardian",n:"Sternenuhr-Wächter"},
  {k:"creature_grindstone_golem",n:"Schleifsteingolem"},
  {k:"creature_voidforge_juggernaut",n:"Leerenschmiede-Juggernaut"},
  {k:"creature_runic_jar",n:"Runenkrug"},
  {k:"creature_dragon_whelp",n:"Drachenwelpe"},
  {k:"creature_dragon_pup_litter",n:"Drachen-Wurfgeschwister"},
  {k:"creature_wyrmling_basilisk",n:"Basilisken-Welpe"},
  {k:"creature_chromatic_drake_red",n:"Rot-Drache"},
  {k:"creature_chromatic_drake_white",n:"Frost-Drache"},
  {k:"creature_chromatic_drake_black",n:"Säure-Drache"},
  {k:"creature_chromatic_drake_green",n:"Gift-Drache"},
  {k:"creature_chromatic_drake_blue",n:"Blitz-Drache"},
  {k:"creature_ancient_dragon_lord",n:"Uralter Drachenfürst"},
  {k:"creature_boss_forest_old_mother",n:"Alte Mutter des Waldes"},
  {k:"creature_boss_swamp_witchking",n:"Sumpf-Hexenkönig"},
  {k:"creature_boss_mountain_avalanche_giant",n:"Lawinen-Riese"},
  {k:"creature_boss_desert_pharaoh_revenant",n:"Pharao-Wiedergänger"},
  {k:"creature_boss_volcano_smith_demon",n:"Vulkan-Schmiededämon"},
  {k:"creature_boss_dungeon_undying_king",n:"Unsterblicher König"},
  {k:"creature_boss_river_kelpie_queen",n:"Kelpie-Königin"},
  {k:"creature_boss_coast_kraken_arm",n:"Kraken-Arm"},
  {k:"creature_boss_capital_traitor_general",n:"Verräter-General"},
  {k:"creature_boss_sky_bound_roc",n:"Wolken-Roc"},
  {k:"creature_bloodmoon_revenant",n:"Blutmond-Wiedergänger"},
  {k:"creature_plague_carrier_villager",n:"Pesttragender Dorfbewohner"},
  {k:"creature_storm_caller_djinn",n:"Sturmrufer"},
  {k:"creature_wildfire_pyre_imp",n:"Brandkobold"},
  {k:"creature_dying_sun_shade",n:"Schatten der sterbenden Sonne"},
  {k:"creature_quake_burrower",n:"Bebenwurm"},
  {k:"creature_locust_queen",n:"Heuschrecken-Königin"},
  {k:"creature_poisoned_spring_horror",n:"Brunnenhorror"},
  {k:"creature_bloodmoon_alpha_wolf",n:"Blutmond-Leitwolf"},
  {k:"creature_silent_pilgrim_white",n:"Weißer Pilger"},
  {k:"creature_clockwork_messenger",n:"Uhrwerks-Bote"},
  {k:"creature_starfall_traveller",n:"Sternfallreisender"},
  {k:"creature_old_god_avatar_fragment",n:"Götter-Fragment"},
  {k:"creature_dream_walker",n:"Traumwandler"},
  {k:"creature_riding_horse_brown",n:"Reitpferd, braun"},
  {k:"creature_riding_horse_war",n:"Schlachtross"},
  {k:"creature_war_wolf",n:"Kampfwolf"},
  {k:"creature_falcon_companion",n:"Falke-Begleiter"},
  {k:"creature_pack_ox",n:"Lastochse"}
];
